### ISSUE TITLE
Upgrade phpMailer

### ISSUE THREAD

**Issue by mindblender** [phpcollab/phpcollab#11]
Update external library to fix potential bugs/issues

**Comment by jpen365** [comment]
It doesn't look like the changes made in March 2015 have been migrated back to the files hosted at Sourceforge. Should those files be updated? It looks like there are still quite a few weekly downloads from Sourceforge.

**Comment by mindblender** [comment]
Hi, no the files on Sourceforge have not been updated yet.  Will update them when we do the next release for PHP 5 support.
