### ISSUE TITLE
Problem with display Files in a Project

### ISSUE THREAD

**Issue by jovalley** [phpcollab/phpcollab#18]
When I add a file, whatever kind it is, this is not visible in the project view . When a task is added, if the files are . Can you help me ?, thanks !

**Comment by mindblender** [comment]
@jovalley Could you check your php error_log and see what error is being shown?

Are you seeing anything at all or just a white screen?

What version of phpCollab are you running and what version of PHP?

Thanks!

**Comment by jovalley** [comment]
Hi, thanks for you response. I have PHP 5.3, phpCollab Version is 2.5.1.
If you see the picture, in Linked Files (or Archivos Adjuntos In Spanish) dont show nothing and i added 2 files there.
![problem](https://cloud.githubusercontent.com/assets/16902384/12612959/23281a3c-c4d5-11e5-8467-59906d95e1db.PNG)

Now, if i put a linked file in a Task for example, dont have problem., so I think that may be the problem is displaying the File in View Project.
![problem2](https://cloud.githubusercontent.com/assets/16902384/12613050/c0185dac-c4d5-11e5-9545-99281715e4d7.PNG)

Regards,
Jonathan

**Comment by mindblender** [comment]
Hi Jonathan,

Thank you for the screenshots.  I will take a look and see what I can find out.

Regards,
Jeff

**Comment by jovalley** [comment]
Ok perfect!, really thanks! i wait for you reply

Regards,
Jonathan

**Comment by mindblender** [comment]
Hi Jonathan,

Just curious, was this an existing install or a new install?  I think I found the problem, just trying to find out how it happened :)

Thanks,
Jeff

**Comment by jovalley** [comment]
Hi Jeff, is a new install...

Thanks,
Jonathan

**Comment by mindblender** [comment]
Ok.  I know what the problem is.  Looking at a solution.

**Comment by jovalley** [comment]
Perfect!, really thanks!, wait for that

Regards,
Jonathan

**Comment by mindblender** [comment]
Hi @jovalley 

The master branch has been updated with a lot of changes in the code structure/logic.  It should stil be compatible with your existing database if you want to give it a try and see if it fixes your issue.  Please note that the master branch is NOT an official release so you are highly recommended to backup your installation first.
