### ISSUE TITLE
PANIC! Error during connection on server MySQL.

### ISSUE THREAD

**Issue by gibranlp** [phpcollab/phpcollab#21]
I can't find the way to install PhpCollab i always get this error.

v2.5.1

**Comment by mindblender** [comment]
Hi @gibranlp,

Is this a new install of an upgrade?  Have you verified that the MySQL user/password, and MySQL server address are correct in the includes/settings.php file?

If possible, could you check the error logs on your web server and see if it give any more information?

Thanks!

**Comment by mindblender** [comment]
Closing due to no response.  Please reopen if you are still having this problem
