### ISSUE TITLE
Change password on „Forgot password ?” page should happen somehow after and only if the e-mail was successfully sended.

### ISSUE THREAD

**Issue by florinj** [phpcollab/phpcollab#25]
This is a major bug.
If the e-mail can not be sent, someone can lose the account because the password will not be sent and the password change already happened in database.
A more secure approach would be to send a volatile change link that will open a webpage where the new password can be entered.

**Comment by mindblender** [comment]
Thanks for letting us know about this issue.  We will add this as an enhancement in v3
