### ISSUE TITLE
Language selection not working in Firefox. In all other tested browsers works.

### ISSUE THREAD

**Issue by florinj** [phpcollab/phpcollab#26]
Hi
The language selection does not work in my Firefox browser. It is always set to „en”.
I am a linux user - Ubuntu-Mate 14.04 LTS / 64bit.
I've installed PhpCollab using nginx + php5-fpm + MySQL.
**nginx virtual host config**
```
...
        location /management/ {
            location ~* ^.+\.(svg|svgz|jpg|jpeg|gif|css|png|js|ico|html|woff|ttf|view)$ {
                access_log        off;
                expires           30d;
            }

            # rewrite any uri to /management/index.php?query
            try_files ($uri|$uri/) /management/index.php?$args;

            location ~* ^(.+/index\.php)(/|$) {
                fastcgi_index  index.php;
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include        fastcgi_params;
                fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_read_timeout 1500;
                fastcgi_intercept_errors off;
            }
        }
...
```
The address is like **http://&lt;domain name&gt;/management/**
Tested browsers: Firefox 50.1.0(not working), Chromium 53.0.2785.143(ok), Opera 42.0.2393.137(ok), Google Chrome 53.0.2785.89(ok), Vivaldi 1.2.490.43(ok).
Also I've take a look at the translation files. IMHO that sort of translation should be changed to gettext or some other well known type. When you look at the source you must also look at the translation file and this is a high time consuming operation.

**Comment by mindblender** [comment]
@florinj Thanks for letting me know about this.  I will take a look at it.

**Comment by mindblender** [comment]
In regards to the translation files, there is a plan to move them to gettext format in the next version.

**Comment by florinj** [comment]
By the way, the selection I've mentioned before, was about the language default selection from the install phase.
Besides that, I've discovered that changing the language using the drop list from the login page also doesn't work. In Firefox stays fixed on English and in the other browsers stays fixed on to whatever the default language was previously chosen.

**Comment by mindblender** [comment]
What version of PhpCollab are you using?

**Comment by florinj** [comment]
2.5.1 from sourceforge

**Comment by mindblender** [comment]
I just tested and if the default language is set in the settings.php file, it selects that by default.  If you change the language in the drop-down on the login page, the subsequent pages should display in that language.

@florinj could you explain more about the expected behavior for the language drop-down list?

Thanks

**Comment by mindblender** [comment]
Closing issue. Please re-open, or create a new one if problem still persists.
