### ISSUE TITLE
Invoices page list per client wrongly display all the invoices from all the clients.

### ISSUE THREAD

**Issue by florinj** [phpcollab/phpcollab#27]
I've created 2 clients with their own projects. But when you try to display client invoices (tested in admin) you will see that in each client invoices list page are displayed all the invoices from all the clients.
Should display only the client invoices according to the breadcrumb:
**Clients / &lt;client X&gt; / Invoices / Open | Sent | Paid**
invoice1 - client X
invoice2 - client X
............................

**Comment by mindblender** [comment]
Thanks, we will look into this and make sure invoices are filtered appropriately

**Comment by mindblender** [comment]
This is a bug. 

From looking at it, I believe logic is getting invoices for all projects that the current user is owner of, instead of by the client id.  This will be fixed in the next release.
