### ISSUE TITLE
Saved session in „members” table generates session errors when loging the same user simultaneous  from different browsers/computers.

### ISSUE THREAD

**Issue by florinj** [phpcollab/phpcollab#28]
It is a good thing to save in db the session id per member/user but only if you want to deny simultaneous loggings for the same user across multiple computers/browsers. Those errors should transform in ”User already logged!” and the deny should remain in function until the other user has logged out when, also, the session id must be deleted from the members table. Now a new logging attempt from another browser/computer does a forced logout( by session error) for the current logged user.

**Comment by mindblender** [comment]
Will look into this.  thanks
