### ISSUE TITLE
After installation certain Tables not found

### ISSUE THREAD

**Issue by DrMartinus** [phpcollab/phpcollab#33]
- [] phpCollab version used
2.6.1
- [] PHP version (e.g. 5.3, 7.x)
5.6
- [] Web server and version (Apache, nginx)
Apache 2.4
- [] Steps to duplicate the problem
After installation, the first login results in the following error:
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: 
Base table or view not found: 1146 Table 'phpcollab.organizations' doesn't exist' in /pathto/phpcollab/classes/Database.php:86 
Stack trace: #0 /pathto/phpcollab/classes/Database.php(86): 
PDOStatement->execute(NULL) #1 /pathto/phpcollab/classes/Database.php(111):
phpCollab\Database->execute() #2 /pathto/phpcollab/classes/Members/MembersGateway.php(60): 
phpCollab\Database->single() #3 /pathto/phpcollab/classes/Members/Members.php(31): 
phpCollab\Members\MembersGateway->getMemberByLogin(Array) #4 /pathto/phpcollab/general/login.php(123): 
phpCollab\Members\Members->getMemberByLogin(Array) #5 {main} thrown in /pathto/phpcollab/classes/Database.php on line 86 
```
I have set the prefix for tables to "phpcoll_", and there is a table called "phpcoll_organizations". Hence I am curious why it says that a table "phpcollab.organizations" is missing. In the above error message, I shortened the path a bit in order to  keep it a bit private.
- [] Stacktraces and phpCollab/PHP DEBUG logs where appropriate.
Sorry, I don't know where to find them.

**Comment by mindblender** [comment]
Is this a new install or an upgrade?

**Comment by mindblender** [comment]
Can you verify that the DB tables were created?

**Comment by mindblender** [comment]
Could be a bug with the table prefix.  I'll take a look and let you know what I find out.

**Comment by DrMartinus** [comment]
![screenshot_20180506_071129](https://user-images.githubusercontent.com/39009855/39670070-ffd7573a-50fc-11e8-9f64-3ff5837c43f6.png)

Here is the list of all tables that were created by phpcollab.

**Comment by mindblender** [comment]
I was able to reproduce.  Will investigate and find a solution.  Thanks!

**Comment by mindblender** [comment]
This has been fixed and will be in the next release.
