### ISSUE TITLE
Hyperlink for appointment doesn't work correctly

### ISSUE THREAD

**Issue by mmmathias** [phpcollab/phpcollab#37]
phpCollab version: v2.6.4

PHP version: any

Web server and version: any

Steps to duplicate the problem:
From calendar dayList perform click on any appointment

Solution:
In ./calendar/viewcalendar.php Line 548:
`
//	MBUD 20190408
//	Hyperlink funktioniert nicht / hyperlink doesn't work
//	$ vor url-param entfernen / removed $ before url-param

$block1->cellRow($blockPage->buildLink("../calendar/viewcalendar.php?$dateEnreg=" . $item['cal_id'] . "&type=calendDetail&dateCalend=$dateCalend", $item['cal_shortname'], 'in'));

$block1->cellRow($blockPage->buildLink("../calendar/viewcalendar.php?dateEnreg=" . $item['cal_id'] . "&type=calendDetail&dateCalend=$dateCalend", $item['cal_shortname'], 'in'));
`

**Comment by mindblender** [comment]
@mmmathias Could you please issue a pull request with this fix?  thanks!
