### ISSUE TITLE
Notification of a new revision, no work

### ISSUE THREAD

**Issue by Vnonni** [phpcollab/phpcollab#39]
Update
PHP version 7.3.6
PhpCollab v2.6.4

and now 
when I create a review, the news via email does not start
thanks

**Comment by mindblender** [comment]
@Vnonni Thanks for the feedback.  There are several issues with using phpCollab and 7.3.x.  I am looking into them, but it will be awhile before full 7.3.x support is in place.  It should be working on 7.2.x though.  Please let us know if the same issue happens there.  thanks!

**Comment by Vnonni** [comment]
Dear Jeff
many thanks for your answer

we stepped back to ver. 7.2.20 as you suggested, 
unfortunately we encounter the same issues we already reported:
•	the notification mails sent for any new object uploaded don't report the comments inserted by who uploaded the file
•	no notification mail is sent when uploading a revision of an existing object
both things worked perfectly before this update (we had made a change to include comments in notification mails)
we've also tried to recover the class.phpmailer.php that worked finely before, unsuccessfully

any other suggestion?
many thanks in advance

**Comment by mindblender** [comment]
Hi @Vnonni 

Sorry you are experiencing the same issue in php 7.2.  

Could you please provide a detailed steps/click path to reproduce the issue?  I'm not clear on what you mean by "object" or what section of the app the issue is in.

**Comment by Vnonni** [comment]
[We use very frequently the feature.docx](https://github.com/phpcollab/phpcollab/files/3396645/We.use.very.frequently.the.feature.docx)

**Comment by mindblender** [comment]
@Vnonni Thanks for that information.  I will take a look and see if I can find the problem.  I'll post back my finding.

**Comment by mindblender** [comment]
@Vnonni I believe I have fixed the missing subject when a new file is added.  However, I looked back at the old code and could not find any instances where a notification was being sent when a file was updated.  I agree with you that that would be handy to know and will add that functionality in so when a file is approved, updated, etc a notification will go out.

I will also add in the comment field to the emails to make them more useful.

Thanks for the feedback and bringing these issues to my attention.

**Comment by Vnonni** [comment]
Dear Team?, Jeff? 
we are using PHPcollab since long on a Windows 2008 server
until the version 2.5.15 of PHPcollab and 5.6 of PHP everything worked fine, and we introduced also some improvements that you later bought as suggestions:
1) notification message sent when a revision of a file is uploaded, and 
2) comments inserted when uploading a file or a revision are reported on the related notification message  

now, after having upgraded PHP to ver. 7.3.12 and PHPcollab to ver. 2.7 nothing works any more
in particular: 
- when uploading a file or a revision, this is not saved on the file system
- notifications aren't sent any more

we made several attempts, first with the same configuration of permissions that we used in the last working installation, then giving complete control to the user (a risky situation, however), but in all cases we meet the same problems 

if we downgrade the environment to the last working versions of PHP and PHPcollab, everything works fine even with restricted permissions, but this is undoable because of security problems of older versions of PHP

we can document in detail our attempts, if this may help you, but it seems like the script Util.php don't create the destination folders for the files

as you can imagine, we're blocked because of this issue 

thank you in advance for your support

kind regards

**Comment by mindblender** [comment]
Hi @Vnonni thanks for the detailed feedback.  I will take a look at the functionality and get a fix for it soon.  I am planning on doing several fixes in the next few weeks and hopefully get a patch out.  I'll keep this issue updated as I make progress.

**Comment by mindblender** [comment]
@Vnonni you mentioned that you had made some enhancements to the codebase?  Would you be willing to contribute those?  If so, please submit a pull request and we will take a look and see about getting them added.  Thanks!

**Comment by mindblender** [comment]
@Vnonni I believe I have a fix for the first issue you are seeing.  However, for the second issue, regarding a notification when a revision is added, I did not see any code that would send a notification.  Perhaps that is a feature/mod that you implemented?

**Comment by mindblender** [comment]
@Vnonni Just a heads up that I have added a new notification when a file revision gets added to be sent out via email.  Also, I believe your other issue has been fixed.
