### ISSUE TITLE
password reset doesn't send new password

### ISSUE THREAD

**Issue by algores** [phpcollab/phpcollab#45]
Dear mindblender as you can see from attached screenshot password reset doesn't send new password but database password field is updated

- Centos 6.10 (Plesk Obsidian 18.0.21)
- phpCollab 2.7.0 (fresh installation)
- Apache 2.2.15 (nginx as reverse proxy)
- tested with PHP version 7.1,7.2,7.3 fastcgi and fpm
- tested with all login methods: PLAIN, MD5, CRYPT 

<img width="1066" alt="Screenshot 2019-12-29 10 56 06" src="https://user-images.githubusercontent.com/26186174/71555251-764d6c80-2a2a-11ea-92a6-fc5aba072b54.png">

Thank you

**Comment by mindblender** [comment]
Thank you for letting me know about this.  I'll take a look and get it fixed.
