### ISSUE TITLE
password with _ character not accepted

### ISSUE THREAD

**Issue by algores** [phpcollab/phpcollab#46]
Dear mindblender,
password with  "_ " character is not accepted, as you can see from attached screenshot, a strange password is generated in the table field
 
- Centos 6.10 (Plesk Obsidian 18.0.21)
- phpCollab 2.7.0 (fresh installation)
- Apache 2.2.15 (nginx as reverse proxy)
- tested with PHP version 7.1,7.2,7.3 fastcgi and fpm
- tested with all login methods: PLAIN, MD5, CRYPT 

<img width="519" alt="Screenshot 2019-12-29 12 53 03" src="https://user-images.githubusercontent.com/26186174/71556639-7e61d800-2a3b-11ea-9587-bb96e0cd1cad.png">

Thank you

**Comment by mindblender** [comment]
Thank you for letting me know about this.  I'll take a look and get it fixed.

**Comment by mindblender** [comment]
@algores Just tested on my local install of phpC 2.7.1 on PHP 7.2.1 and I was able to create a user with an underscore in the password.

Steps I took to reproduce:
Logged in as admin, went to User Management, clicked Add User.  Filled out the information and used abc_123 as password and it saved it in the database.  Logged out and tried logging in with the newly created user and was able to successfully login.

Could you please provide the steps you were doing to recreate the issue?  thanks!
