### ISSUE TITLE
edit task: comment field

### ISSUE THREAD

**Issue by algores** [phpcollab/phpcollab#48]
Dear mindblender,
when task with comment is modified comment textarea is empty.
I think {$_POST["comments"]} in the tasks/edittask.php line 987 should be "{$comments}" 

Centos 6.10 (Plesk Obsidian 18.0.21)
phpCollab 2.7.0 (fresh installation with data imported)
Apache 2.2.15 (nginx as reverse proxy)
PHP version 7.3.13 fastcgi

Thank you

**Comment by mindblender** [comment]
IT very well could be.  I'll check the code and get it fixed soon.
