### ISSUE TITLE
create report: date not filtered

### ISSUE THREAD

**Issue by algores** [phpcollab/phpcollab#49]
Dear mindblender,
report results (reports/resultsreport.php) doesn't filter "Due Date" and "Complete Date"

Centos 6.10 (Plesk Obsidian 18.0.21)
phpCollab 2.7.0 (fresh installation with data imported)
Apache 2.2.15 (nginx as reverse proxy)
PHP version 7.3.13 fastcgi

Thank you

**Comment by mindblender** [comment]
thanks, I'll take a look!
