### ISSUE TITLE
MM_getButtonWithName is not defined

### ISSUE THREAD

**Issue by vanbeck** [phpcollab/phpcollab#50]
# Issue Report

phpCollab version used: 2.7.2
PHP version 7
Web server and version Apache
Steps to duplicate the problem: click on any button

**Comment by mindblender** [comment]
@vanbeck Could you please provide more information.  I am unable to reproduce an "is not defined" error.

**Comment by vanbeck** [comment]
Hi, I find the issue.
Is not a problem of PHPCOLLAB but an issue with debian.
I need to purge javascript-common because it had made an incorrect alias.


<https://www.facebook.com/imcalternancerandstad>



Le mar. 3 mars 2020 à 07:43, Jeff Sittler <notifications@github.com> a
écrit :

**Comment by mindblender** [comment]
Thanks for letting us know.
