### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by davideferretto** [phpcollab/phpcollab#54]
Hello! I'm a happy PHPCOLLAB user from Italy.
Is the first time that I use Git to send an error but i'm not a developer and i cant solve this problem :(

SITUATION

- [] phpCollab version used: 2.7.2
- [] PHP version (e.g. 5.3, 7.x): 7.0
- [] Web server and version (Apache, nginx): ngix
- [] Steps to duplicate the problem:
OPEN A PROJECT --> INSERT A FILE ATTACHED INTO A TASK --> TRY TO DOWNLOAD IT
- [] Stacktraces and phpCollab/PHP DEBUG logs where appropriate.: 
Fatal error: Uncaught TypeError: Return value of phpCollab\Files\GetFile::setFilesPath() must be an instance of phpCollab\Files\void, none returned in /volume1/web/collab/classes/Files/GetFile.php on line 30 TypeError: Return value of phpCollab\Files\GetFile::setFilesPath() must be an instance of phpCollab\Files\void, none returned in /volume1/web/collab/classes/Files/GetFile.php on line 30 Call Stack: 0.0003 374600 1. {main}() /volume1/web/collab/linkedcontent/accessfile.php:0 0.0475 3244624 2. phpCollab\Files\GetFile->setFilesPath() /volume1/web/collab/linkedcontent/accessfile.php:29

Thanks for any suggestion! Have a nice day!

**Comment by mindblender** [comment]
Hi @davideferretto thanks for letting us know.  we will take a look at the issue.

**Comment by davideferretto** [comment]
Thanks a lot!

Inviato da iPhone

**Comment by mindblender** [comment]
@davideferretto This should be fixed in the latest release.  Could you please install the latest version and re-test?  thanks!

**Comment by davideferretto** [comment]
Thanks for your reply!
I tried to install the new version in the same server as mentioned and i receive this error :(

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /volume1/web/collab/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 44

**Comment by mindblender** [comment]
@davideferretto 
hmm I haven't seen that error in my testing. If you don't have a "logs" directory in the root of the project, could you create one 
and make sure it is writeable.  Then try again and see if you get the same error.  

Thanks!
