### ISSUE TITLE
Fix repository info link

### ISSUE THREAD

**Issue by ychavoya** [phpcollab/phpcollab#60]
Hey! This is nothing about the code (great work!), but something small about the repository info on github 😄 

Currently it says `https:/phpcollab.com` when it should be `https://phpcollab.com`. 

Just thought you might want to know 😅 

![image](https://user-images.githubusercontent.com/7907338/120253468-09588a80-c24d-11eb-8e21-53d8d8bcc6c2.png)

**Comment by mindblender** [comment]
Fixed.  Thanks @ychavoya
