### ISSUE TITLE
Update settings error

### ISSUE THREAD

**Issue by Machiuka** [phpcollab/phpcollab#68]
When try to update settings from Administration / Project settings and configuration, the file updatesettings.php gives an error.

**Comment by mindblender** [comment]
Could you please provide additional information regarding the error you are seeing and what steps you performed to produce the error.  Thanks!

**Comment by Machiuka** [comment]
When you change debugging settings from 400 Prod to 100 Debug it shows the error message phpcollab appears to have fallen down

**Comment by Machiuka** [comment]
Little update: Changing that setting, from 400 to 100 is a fatal flaw. Entire site become unreachable. I'll reinstall the app and see if the problem repeat.

**Comment by Machiuka** [comment]
Another update: Entering in that menu and clicking "Save" button crashed the site, even if no other selections are made.

**Comment by Machiuka** [comment]
The problem is that in the ~/includes/settings.php the password to access database is altered after that operation. Putting back the correct password allow to access the site again.

**Comment by mindblender** [comment]
@Machiuka What version of phpC are you using?

**Comment by mindblender** [comment]
Closing this due to lack of response and unable to reproduce.  Please re-open if it is still an issue
