### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [phpcollab/phpcollab#77]
@mindblender 
Few security vulnerability has been reported to huntr against your repo . It has been 6 month since reported but still no response .
Plz validate them here .
If you are repo maintainer then you can view the report  . Plz let me know if you have any problem to validate

**Comment by mindblender** [comment]
@ranjit-git I responded multiple times to your previous emails requesting further information, yet I received no response.  Please reach out using the proper methods for reporting/inquiring about security related issues.  Thanks

**Comment by mindblender** [comment]
@ranjit-git Issues are not the proper place to report security issues.  Please follow the proper procedures outlined here: https://github.com/phpcollab/phpcollab/security/policy

**Comment by ranjit-git** [comment]
@mindblender  vulnerabiltiy details has been to your provided email address . Plz validate them .
If you having problem to view the report then plz let me know .
Also if you having issue to reproduce the bug on your site or some link not working for you then plz comment in that report so that i can get notification and can assist you further

**Comment by ranjit-git** [comment]
Here are  high severity bug reported like remote-code-execution ,xss etc
https://huntr.dev/bounties/5bdfe24f-5407-41da-a4d8-462cbe8bcca9/
https://huntr.dev/bounties/218ffdc2-7c5c-412c-b286-ea74460d31f1/
https://huntr.dev/bounties/b1c7c400-46c6-4c3a-9530-a195e327f144/
https://huntr.dev/bounties/a55f445f-1b52-45b4-b7d7-cce1ccaae45f/
https://huntr.dev/bounties/4cc76d34-ae6f-4a9a-86c8-64776dd61621/

you can view the report via signup or without signup with magick link that has been sent to your mail .
Having issue to read the report then make a comment in those report
