### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ISharlsI** [phpcollab/phpcollab#78]
Hi, firstly I would like to say that this is not a general issue or a bug, it is more like a problem with my installation because I'm new in Linux and phpCollab, so if this does not belong here please let me know where I can get help. Basically when I'm in the setup page, after filling in the fields and pressing the save button I get an error saying "We had a problem completing the request. Please check and try again." I checked the log file, and it says that I have an error trying to connect to the database. I'm using mysql-server, I created a database called "phpcollab", that was all I did as the instructions said. 

- [] phpCollab 2.10.3
- [] PHP version 7.4
- [] Web server and version Apache2
![1](https://user-images.githubusercontent.com/88348813/151034695-a613dec1-8752-43a6-92f8-d41415c46c49.jpg)

**Comment by mindblender** [comment]
Hi @ISharlsI Sorry you are having problems getting phpCollab installed.

Sounds like there is a connection issue with either user permissions or the web server can't connect to the DB server.

Could you please provide some additional information?

1. Did you create the DB user and give it permission to access the 'phpcollab' database?
2. Is the Database hosted on the same server?

Thanks!

**Comment by mindblender** [comment]
@ISharlsI I am glad that you found the issue to the problem.  Based on the information you have provided, I will add some additional checks in the installation process to make sure the system has the necessary libraries required.
