### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by eusuntacum** [phpcollab/phpcollab#88]
Hi,
please I need a little help:
I'm running the latest version and I get the following error when I try to access the /projects_site/home.php 
it is a new fresh install no softaculos.

phpcollab.log:
FATAL ERROR (2): Error: Call to a member function getPhasesByProjectIdAndIsCompleted() on null in mysit/phpcollab/projects_site/home.php:122
Stack trace:
#0 {main}

![image](https://user-images.githubusercontent.com/34725452/203403488-a90b60e8-6983-4ef0-ba6f-a487368b7237.png)

**Comment by mindblender** [comment]
@eusuntacum Are you able to access the main phpCollab site (i.e. not the project site)?  Also, do you have phases enabled for that project?

**Comment by mindblender** [comment]
It is most likely a change in the file.  Are you comfortable updating files manually?

**Comment by eusuntacum** [comment]
Yes. Pls. U have a sollution?

**Comment by mindblender** [comment]
Make a backup of your `projects_site` files, and replace them from the repo here: https://github.com/phpcollab/phpcollab/tree/master/projects_site

**Comment by eusuntacum** [comment]
thank you,
I replaced it but I still got the following error at "/projects_site/home.php"
![image](https://user-images.githubusercontent.com/34725452/206860131-e674ebc9-0191-42f0-a00e-5d9f5f81068d.png)

**Comment by mindblender** [comment]
Sorry you are still having problems.  I'll take a look and try to reproduce.  Could you please provide any error messages from the log file?

**Comment by mindblender** [comment]
I think I have reproduced the issue locally.  I will debug and let you know what I find out.

**Comment by eusuntacum** [comment]
Thank you very much!
attached you find the logo.
to be something from the membership permission?
[phpcollab.log](https://github.com/phpcollab/phpcollab/files/10200858/phpcollab.log)

Thank you very much!

**Comment by eusuntacum** [comment]
thank you very much and I'm waiting for good news from you :)

**Comment by mindblender** [comment]
Check out PR #89 and see if that fixes your problem.

**Comment by mindblender** [comment]
@eusuntacum Did you get a chance to test out PR #89 so see if it fixed your problem?

**Comment by mindblender** [comment]
@eusuntacum Any updates on testing the PR?
